#!/usr/bin/env sh
set -e

: "${SILETAG:=v0.10.15}"

DESC=$(git describe --long --tags --always)

RUNTIME_DEPS='words'

: "${DOCKER_BUILDKIT:=1}"
export DOCKER_BUILDKIT

docker build \
	--build-arg SILETAG="$SILETAG" \
	--build-arg VCS_REF="${1:-$DESC}" \
	--build-arg RUNTIME_DEPS="$RUNTIME_DEPS" \
	--tag $IMAGE_NAME \
	./
